// Generated by scripts/gen-block-types.ts - do not edit; run `pnpm gen`.
//
// BlockPropTypes maps every default block name to the exact TypeScript shape
// of its props, derived from the same PropSpec data the validator uses.

import type { JsonLiteral } from './ast.js';
import type { Button, Chart, Stack, Stat } from './blocks.js';
import type { InferBlockProps } from './schema.js';

export interface BlockPropTypes {
  Box: Record<string, never>;
  Stack: {
    direction?: 'vertical' | 'horizontal';
    align?: 'start' | 'center' | 'end' | 'baseline' | 'stretch';
    justify?: 'start' | 'center' | 'end' | 'between';
  };
  Grid: { cols?: number };
  Divider: Record<string, never>;
  Card: { tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle' };
  Text: {
    tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle';
    variant?: 'body' | 'label' | 'caption';
  };
  Heading: { level?: number };
  Markdown: Record<string, never>;
  Image: { src?: string; alt: string };
  Icon: { name: string; tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle' };
  Link: { href: string };
  Badge: { tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle'; icon?: string };
  Tag: { tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle'; icon?: string };
  Avatar: { name?: string; initials?: string };
  AvatarGroup: Record<string, never>;
  Code: { language?: string };
  Callout: { tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle'; icon?: string };
  Button: { variant?: 'primary' | 'secondary' | 'subtle' | 'danger'; icon?: string };
  Input: { label?: string; placeholder?: string; value?: string };
  Select: { label?: string; options?: string[] };
  MultiSelect: { label?: string; options?: string[] };
  Autocomplete: { label?: string; options?: string[] };
  Checkbox: { label?: string };
  Radio: { label?: string; options?: string[] };
  Toggle: { label?: string };
  Slider: { label?: string; min?: number; max?: number; step?: number };
  DatePicker: { label?: string };
  ColorPicker: { label?: string };
  FilePicker: { label?: string };
  Rating: { label?: string; max?: number };
  TagInput: { label?: string };
  Field: { label?: string };
  Disclosure: { label?: string };
  Accordion: { items: string[] };
  Tabs: { items: string[]; active?: string };
  Steps: { items: string[]; current?: number };
  SegmentedControl: { options: string[] };
  Progress: { value: number; label?: string };
  Empty: { label?: string };
  Video: { src?: string; alt: string };
  Audio: { src?: string; alt?: string };
  Carousel: Record<string, never>;
  DataTable: { columns: string[]; rows: string[][] };
  List: Record<string, never>;
  Tree: { items: Array<{ label: string; children?: Array<Record<string, JsonLiteral>> }> };
  Board: { items: Array<{ title: string; column?: string }> };
  Timeline: {
    items: Array<{
      date?: string;
      title: string;
      description?: string;
      tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle';
    }>;
  };
  Calendar: { items: Array<{ date: string; title: string }> };
  Stat: { label: string; value: string; tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle' };
  Chart: {
    alt: string;
    type: 'bar' | 'line' | 'area' | 'donut' | 'radar' | 'gauge' | 'scatter';
    data: Array<{ label: string; value: number }>;
  };
  VegaChart: { alt: string; spec: JsonLiteral };
  Diagram: {
    alt: string;
    direction?: 'right' | 'down';
    nodes: Array<{
      id: string;
      label?: string;
      kind?: 'service' | 'store' | 'queue' | 'client' | 'external' | 'concept' | 'code';
      tone?: 'ok' | 'warn' | 'bad' | 'primary' | 'subtle';
    }>;
    edges?: Array<{ from: string; to: string; label?: string; dashed?: boolean }>;
  };
  Canvas: { alt: string };
  Embed: { src?: string; alt?: string };
}

// Compile-time agreement with InferBlockProps for representative blocks: a
// drift between the generator and the inference fails typecheck here.
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
  ? true
  : false;
type Assert<T extends true> = T;
export type BlockPropTypesAgree = [
  Assert<Equal<BlockPropTypes['Button'], InferBlockProps<typeof Button>>>,
  Assert<Equal<BlockPropTypes['Chart'], InferBlockProps<typeof Chart>>>,
  Assert<Equal<BlockPropTypes['Stack'], InferBlockProps<typeof Stack>>>,
  Assert<Equal<BlockPropTypes['Stat'], InferBlockProps<typeof Stat>>>,
];
