// Generates packages/ts/mosaic-core/src/blocks.gen.ts: the BlockPropTypes
// interface mapping every default block name to its exact inferred prop type.
// Run from the repo root with `pnpm gen` (Node strips the types natively);
// the emitted file is committed and CI diffs it for staleness.

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { fileURLToPath } from 'node:url';

// Node resolves specifiers literally, and the package sources import with .js
// extensions (bundler-style); retry failed relative .js imports as .ts.
registerHooks({
  resolve(specifier, context, nextResolve) {
    try {
      return nextResolve(specifier, context);
    } catch (error) {
      if (specifier.startsWith('.') && specifier.endsWith('.js')) {
        return nextResolve(`${specifier.slice(0, -3)}.ts`, context);
      }
      throw error;
    }
  },
});

type PropSpec = {
  type: string;
  required?: boolean;
  values?: readonly string[];
  shape?: Readonly<Record<string, PropSpec>>;
};
type BlockDefinition = { name: string; props: Readonly<Record<string, PropSpec>> };

const blocksModule = (await import('../packages/ts/mosaic-core/src/blocks.ts')) as {
  defaultBlocks: readonly BlockDefinition[];
};
const { defaultBlocks } = blocksModule;

let usesJsonLiteral = false;

// Mirrors InferBlockProps in src/schema.ts; the emitted file asserts the two
// stay identical for representative blocks.
function propType(spec: PropSpec): string {
  switch (spec.type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enum':
      return (spec.values ?? []).map((v) => `'${v}'`).join(' | ') || 'string';
    case 'string[]':
      return 'string[]';
    case 'number[]':
      return 'number[]';
    case 'string[][]':
      return 'string[][]';
    case 'record[]':
      return `Array<${recordType(spec)}>`;
    case 'record':
      return recordType(spec);
    default:
      usesJsonLiteral = true;
      return 'JsonLiteral';
  }
}

function recordType(spec: PropSpec): string {
  if (!spec.shape) {
    usesJsonLiteral = true;
    return 'Record<string, JsonLiteral>';
  }
  return objectType(spec.shape);
}

function objectType(props: Readonly<Record<string, PropSpec>>): string {
  const members = Object.entries(props).map(
    ([name, spec]) => `${name}${spec.required ? '' : '?'}: ${propType(spec)}`,
  );
  return `{ ${members.join('; ')} }`;
}

function blockType(def: BlockDefinition): string {
  if (Object.keys(def.props).length === 0) return 'Record<string, never>';
  return objectType(def.props);
}

const entries = defaultBlocks.map((def) => `  ${def.name}: ${blockType(def)};`);
// Alphabetical so the emitted import is already organize-imports clean.
const assertNames = ['Button', 'Chart', 'Stack', 'Stat'];

const out = `// Generated by scripts/gen-block-types.ts - do not edit; run \`pnpm gen\`.
//
// BlockPropTypes maps every default block name to the exact TypeScript shape
// of its props, derived from the same PropSpec data the validator uses.

${usesJsonLiteral ? "import type { JsonLiteral } from './ast.js';\n" : ''}import type { ${assertNames.join(', ')} } from './blocks.js';
import type { InferBlockProps } from './schema.js';

export interface BlockPropTypes {
${entries.join('\n')}
}

// Compile-time agreement with InferBlockProps for representative blocks: a
// drift between the generator and the inference fails typecheck here.
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
  ? true
  : false;
type Assert<T extends true> = T;
export type BlockPropTypesAgree = [
${assertNames
  .map((n) => `  Assert<Equal<BlockPropTypes['${n}'], InferBlockProps<typeof ${n}>>>,`)
  .join('\n')}
];
`;

const outPath = fileURLToPath(
  new URL('../packages/ts/mosaic-core/src/blocks.gen.ts', import.meta.url),
);
writeFileSync(outPath, out);

// Biome owns the repo's formatting; formatting here keeps the emitted file
// byte-stable under `git diff --exit-code` regardless of generator layout.
const format = spawnSync('pnpm', ['exec', 'biome', 'format', '--write', outPath], {
  cwd: fileURLToPath(new URL('..', import.meta.url)),
  stdio: 'inherit',
});
if (format.status !== 0) process.exit(format.status ?? 1);
console.info(`generated ${outPath}`);
